# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addAct.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_addAct(object):
    def setupUi(self, addAct):
        addAct.setObjectName("addAct")
        addAct.resize(460, 340)
        addAct.setStyleSheet("* {\n"
"    background-color: white;\n"
"    font: 12pt \"YaHei Monaco Hybird\";\n"
"}\n"
"QPushButton{\n"
"    background-color: skyblue;\n"
"}\n"
"QLabel{\n"
"    font: 12pt \"YaHei Monaco Hybird\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(addAct)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 50, 320, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_lab = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.name_lab.sizePolicy().hasHeightForWidth())
        self.name_lab.setSizePolicy(sizePolicy)
        self.name_lab.setTextFormat(QtCore.Qt.PlainText)
        self.name_lab.setObjectName("name_lab")
        self.horizontalLayout.addWidget(self.name_lab)
        self.name_le = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.name_le.sizePolicy().hasHeightForWidth())
        self.name_le.setSizePolicy(sizePolicy)
        self.name_le.setBaseSize(QtCore.QSize(220, 30))
        self.name_le.setText("")
        self.name_le.setObjectName("name_le")
        self.horizontalLayout.addWidget(self.name_le)
        self.name_lab_2 = QtWidgets.QLabel(self.centralwidget)
        self.name_lab_2.setGeometry(QtCore.QRect(60, 110, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.name_lab_2.sizePolicy().hasHeightForWidth())
        self.name_lab_2.setSizePolicy(sizePolicy)
        self.name_lab_2.setTextFormat(QtCore.Qt.PlainText)
        self.name_lab_2.setObjectName("name_lab_2")
        self.start_dt = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.start_dt.setGeometry(QtCore.QRect(160, 110, 241, 31))
        self.start_dt.setObjectName("start_dt")
        self.name_lab_3 = QtWidgets.QLabel(self.centralwidget)
        self.name_lab_3.setGeometry(QtCore.QRect(60, 170, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.name_lab_3.sizePolicy().hasHeightForWidth())
        self.name_lab_3.setSizePolicy(sizePolicy)
        self.name_lab_3.setTextFormat(QtCore.Qt.PlainText)
        self.name_lab_3.setObjectName("name_lab_3")
        self.end_dt = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.end_dt.setGeometry(QtCore.QRect(160, 170, 241, 31))
        self.end_dt.setObjectName("end_dt")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(80, 240, 300, 36))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.add_bt = QtWidgets.QPushButton(self.layoutWidget_2)
        self.add_bt.setObjectName("add_bt")
        self.horizontalLayout_6.addWidget(self.add_bt)
        self.return_bt = QtWidgets.QPushButton(self.layoutWidget_2)
        self.return_bt.setObjectName("return_bt")
        self.horizontalLayout_6.addWidget(self.return_bt)
        addAct.setCentralWidget(self.centralwidget)

        self.retranslateUi(addAct)
        QtCore.QMetaObject.connectSlotsByName(addAct)

    def retranslateUi(self, addAct):
        _translate = QtCore.QCoreApplication.translate
        addAct.setWindowTitle(_translate("addAct", "添加活动"))
        self.name_lab.setText(_translate("addAct", "活动名:"))
        self.name_le.setPlaceholderText(_translate("addAct", "请输入活动名"))
        self.name_lab_2.setText(_translate("addAct", "开始时间:"))
        self.name_lab_3.setText(_translate("addAct", "结束时间:"))
        self.add_bt.setText(_translate("addAct", "添加"))
        self.return_bt.setText(_translate("addAct", "返回"))
