# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addUserToAct.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addUser(object):
    def setupUi(self, addUser):
        addUser.setObjectName("addUser")
        addUser.resize(517, 715)
        addUser.setStyleSheet("* {\n"
"    background-color: white;\n"
"    font: 12pt \"YaHei Monaco Hybird\";\n"
"}\n"
"QPushButton{\n"
"    background-color: skyblue;\n"
"}\n"
"QLabel{\n"
"    font: 12pt \"YaHei Monaco Hybird\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(addUser)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(100, 640, 300, 36))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.add_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_6.addWidget(self.add_btn)
        self.return_bt = QtWidgets.QPushButton(self.layoutWidget_2)
        self.return_bt.setObjectName("return_bt")
        self.horizontalLayout_6.addWidget(self.return_bt)
        self.user_tb = QtWidgets.QTableWidget(self.centralwidget)
        self.user_tb.setGeometry(QtCore.QRect(30, 50, 451, 571))
        self.user_tb.setObjectName("user_tb")
        self.user_tb.setColumnCount(0)
        self.user_tb.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 10, 181, 31))
        self.label.setObjectName("label")
        addUser.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(addUser)
        self.statusbar.setObjectName("statusbar")
        addUser.setStatusBar(self.statusbar)

        self.retranslateUi(addUser)
        QtCore.QMetaObject.connectSlotsByName(addUser)

    def retranslateUi(self, addUser):
        _translate = QtCore.QCoreApplication.translate
        addUser.setWindowTitle(_translate("addUser", "添加签到人员"))
        self.add_btn.setText(_translate("addUser", "添加"))
        self.return_bt.setText(_translate("addUser", "返回"))
        self.label.setText(_translate("addUser", "可添加人员:"))
