# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Login(object):
    def setupUi(self, MainWindow_Login):
        MainWindow_Login.setObjectName("MainWindow_Login")
        MainWindow_Login.resize(500, 430)
        MainWindow_Login.setStyleSheet("QLabel, QSplitter, QWidget, QHBoxLayout{\n"
" background-color: white;\n"
"}\n"
"QPushButton{\n"
"    background-color: skyblue;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow_Login)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 80, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Source Han Sans SC")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(90, 130, 321, 191))
        self.splitter.setStyleSheet("")
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Source Han Sans SC")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.un_le = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.un_le.setObjectName("un_le")
        self.horizontalLayout.addWidget(self.un_le)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Source Han Sans SC")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pwd_le = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.pwd_le.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.pwd_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_le.setObjectName("pwd_le")
        self.horizontalLayout_2.addWidget(self.pwd_le)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.login_bt = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.login_bt.setObjectName("login_bt")
        self.horizontalLayout_3.addWidget(self.login_bt)
        self.register_bt = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.register_bt.setObjectName("register_bt")
        self.horizontalLayout_3.addWidget(self.register_bt)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.quit_bt = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.quit_bt.setStyleSheet("")
        self.quit_bt.setObjectName("quit_bt")
        self.horizontalLayout_4.addWidget(self.quit_bt)
        MainWindow_Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_Login)
        self.statusbar.setObjectName("statusbar")
        MainWindow_Login.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_Login)
        self.quit_bt.clicked.connect(MainWindow_Login.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Login)

    def retranslateUi(self, MainWindow_Login):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Login.setWindowTitle(_translate("MainWindow_Login", "登录"))
        self.label_3.setText(_translate("MainWindow_Login", "欢迎登录人脸识别签到系统"))
        self.label.setText(_translate("MainWindow_Login", "帐号: "))
        self.label_2.setText(_translate("MainWindow_Login", "密码: "))
        self.login_bt.setText(_translate("MainWindow_Login", "登录"))
        self.register_bt.setText(_translate("MainWindow_Login", "注册"))
        self.quit_bt.setText(_translate("MainWindow_Login", "退出"))
