# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 601)
        MainWindow.setStyleSheet("* {\n"
"    background-color: white;\n"
"    font: 12pt \"YaHei Monaco Hybird\";\n"
"}\n"
"QPushButton{\n"
"    background-color: skyblue;\n"
"}\n"
"QLabel{\n"
"    font: 12pt \"YaHei Monaco Hybird\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_user_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_user_btn.setGeometry(QtCore.QRect(80, 120, 151, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.add_user_btn.sizePolicy().hasHeightForWidth())
        self.add_user_btn.setSizePolicy(sizePolicy)
        self.add_user_btn.setObjectName("add_user_btn")
        self.add_act_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_act_btn.setGeometry(QtCore.QRect(80, 180, 151, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.add_act_btn.sizePolicy().hasHeightForWidth())
        self.add_act_btn.setSizePolicy(sizePolicy)
        self.add_act_btn.setObjectName("add_act_btn")
        self.open_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_btn.setGeometry(QtCore.QRect(80, 240, 151, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.open_btn.sizePolicy().hasHeightForWidth())
        self.open_btn.setSizePolicy(sizePolicy)
        self.open_btn.setObjectName("open_btn")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(80, 300, 151, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.start_btn.sizePolicy().hasHeightForWidth())
        self.start_btn.setSizePolicy(sizePolicy)
        self.start_btn.setObjectName("start_btn")
        self.quit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.quit_btn.setGeometry(QtCore.QRect(80, 480, 151, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.quit_btn.sizePolicy().hasHeightForWidth())
        self.quit_btn.setSizePolicy(sizePolicy)
        self.quit_btn.setObjectName("quit_btn")
        self.manage_btn = QtWidgets.QPushButton(self.centralwidget)
        self.manage_btn.setGeometry(QtCore.QRect(80, 360, 151, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.manage_btn.sizePolicy().hasHeightForWidth())
        self.manage_btn.setSizePolicy(sizePolicy)
        self.manage_btn.setObjectName("manage_btn")
        self.camera_lab = QtWidgets.QLabel(self.centralwidget)
        self.camera_lab.setGeometry(QtCore.QRect(330, 10, 641, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_lab.sizePolicy().hasHeightForWidth())
        self.camera_lab.setSizePolicy(sizePolicy)
        self.camera_lab.setStyleSheet("border:5px solid rgb(255,170,0);")
        self.camera_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.camera_lab.setObjectName("camera_lab")
        self.act_cb = QtWidgets.QComboBox(self.centralwidget)
        self.act_cb.setGeometry(QtCore.QRect(120, 50, 171, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.act_cb.sizePolicy().hasHeightForWidth())
        self.act_cb.setSizePolicy(sizePolicy)
        self.act_cb.setObjectName("act_cb")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 91, 41))
        self.label.setObjectName("label")
        self.result_lab = QtWidgets.QLabel(self.centralwidget)
        self.result_lab.setGeometry(QtCore.QRect(330, 520, 641, 41))
        self.result_lab.setText("")
        self.result_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.result_lab.setObjectName("result_lab")
        self.manage_msg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.manage_msg_btn.setGeometry(QtCore.QRect(80, 420, 151, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.manage_msg_btn.sizePolicy().hasHeightForWidth())
        self.manage_msg_btn.setSizePolicy(sizePolicy)
        self.manage_msg_btn.setObjectName("manage_msg_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "主界面"))
        self.add_user_btn.setText(_translate("MainWindow", "人脸录入"))
        self.add_act_btn.setText(_translate("MainWindow", "创建活动"))
        self.open_btn.setText(_translate("MainWindow", "打开摄像头"))
        self.start_btn.setText(_translate("MainWindow", "开始检测"))
        self.quit_btn.setText(_translate("MainWindow", "退出系统"))
        self.manage_btn.setText(_translate("MainWindow", "管理当前活动"))
        self.camera_lab.setText(_translate("MainWindow", "摄像头"))
        self.label.setText(_translate("MainWindow", "当前活动:"))
        self.manage_msg_btn.setText(_translate("MainWindow", "管理录入信息"))
