# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manageUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manageUser(object):
    def setupUi(self, manageUser):
        manageUser.setObjectName("manageUser")
        manageUser.resize(517, 715)
        manageUser.setStyleSheet("* {\n"
"    background-color: white;\n"
"    font: 12pt \"YaHei Monaco Hybird\";\n"
"}\n"
"QPushButton{\n"
"    background-color: skyblue;\n"
"}\n"
"QLabel{\n"
"    font: 12pt \"YaHei Monaco Hybird\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(manageUser)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(100, 640, 300, 36))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.delete_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_6.addWidget(self.delete_btn)
        self.return_bt = QtWidgets.QPushButton(self.layoutWidget_2)
        self.return_bt.setObjectName("return_bt")
        self.horizontalLayout_6.addWidget(self.return_bt)
        self.user_tb = QtWidgets.QTableWidget(self.centralwidget)
        self.user_tb.setGeometry(QtCore.QRect(30, 50, 451, 571))
        self.user_tb.setObjectName("user_tb")
        self.user_tb.setColumnCount(0)
        self.user_tb.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 10, 181, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        manageUser.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(manageUser)
        self.statusbar.setObjectName("statusbar")
        manageUser.setStatusBar(self.statusbar)

        self.retranslateUi(manageUser)
        QtCore.QMetaObject.connectSlotsByName(manageUser)

    def retranslateUi(self, manageUser):
        _translate = QtCore.QCoreApplication.translate
        manageUser.setWindowTitle(_translate("manageUser", "管理录入信息"))
        self.delete_btn.setText(_translate("manageUser", "删除"))
        self.return_bt.setText(_translate("manageUser", "返回"))
        self.label.setText(_translate("manageUser", "已录入信息"))
